# Generated by Django 5.1.6 on 2025-02-27 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biscuits', '0002_biscuits_pairing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biscuits',
            name='dunkability',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='biscuits',
            name='taste',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='biscuits',
            name='texture',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
