# Generated by Django 5.1.6 on 2025-03-05 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biscuits', '0003_alter_biscuits_dunkability_alter_biscuits_taste_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biscuits',
            name='image',
        ),
    ]
